stackName: "eksSd"
modelBucketArn: 'arn:aws:s3:::<ML Model S3 Bucket>'
modelsRuntime:
- name: "sdruntime-snapshot"
  namespace: "sdruntime"
  type: "SDWebUI"
  chartRepository: "oci://<AWS Account ID>.dkr.ecr.us-east-1.amazonaws.com/eks-sd/charts/eks-keda-sd"
  chartVersion: "0.1.32" # Version of Helm chart.
  modelFilename: "v1-5-pruned-emaonly.safetensors"
  extraValues:
    sdWebuiInferenceApi:
      inferenceApi:
        image:
          repository: <AWS Account ID>.dkr.ecr.us-east-1.amazonaws.com/eks-sd/inference-api # Image Repository of stable diffusion runtime.
          tag: latest
      queueAgent:
        image:
          repository: <AWS Account ID>.dkr.ecr.us-east-1.amazonaws.com/eks-sd/queue-agent # Image Repository of queue agent.
          tag: latest
      persistence:
        enabled: true
      scaling:
        queueLength: 20 # Target value for queue length. One new instance will be launched when queue launch reaches the value.
        minReplicaCount: 0 # Minimum number of replicas of SD Runtime.
        maxReplicaCount: 5 # Maxinum number of replicas of SD Runtime.
        cooldownPeriod: 300 # The period (in seconds) to wait after the last message before scaling down.
dynamicModelRuntime:
  enabled: false
  namespace: "dynamic"