{{- if .Values.sdWebuiInferenceApi.scaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "sdchart.fullname" . }}-aws-sqs-queue-scaledobject
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
  {{- if .Values.sdWebuiInferenceApi.labels }}
  {{- toYaml .Values.sdWebuiInferenceApi.labels | nindent 4 }}
  {{- end }}
spec:
  cooldownPeriod: {{ .Values.sdWebuiInferenceApi.scaling.cooldownPeriod }}
  maxReplicaCount: {{ .Values.sdWebuiInferenceApi.scaling.maxReplicaCount }}
  minReplicaCount: {{ .Values.sdWebuiInferenceApi.scaling.minReplicaCount }}
  pollingInterval: {{ .Values.sdWebuiInferenceApi.scaling.pollingInterval }}
  scaleOnInFlight: {{ .Values.sdWebuiInferenceApi.scaling.scaleOnInFlight }}
  {{- if .Values.sdWebuiInferenceApi.scaling.extraHPAConfig }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
      {{- toYaml .Values.sdWebuiInferenceApi.extraHPAConfig | nindent 8 }}
  {{- end }}
  scaleTargetRef:
    name: {{ include "sdchart.fullname" . }}-sd-webui-inference-api
  triggers:
  - authenticationRef:
      name: {{ include "sdchart.fullname" . }}-keda-trigger-auth-aws-credentials
    metadata:
      awsRegion: {{ .Values.global.awsRegion }}
      identityOwner: operator
      queueLength: {{ quote .Values.sdWebuiInferenceApi.scaling.queueLength }}
      queueURL: {{ .Values.sdWebuiInferenceApi.queueAgent.sqsQueueUrl }}
    type: aws-sqs-queue
{{- end }}