{{- if and .Values.sdWebuiInferenceApi.scaling.enabled .Values.sdWebuiInferenceApi.isJob }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "sdchart.fullname" . }}-aws-sqs-queue-scaledjob
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
  {{- if .Values.sdWebuiInferenceApi.labels }}
  {{- toYaml .Values.sdWebuiInferenceApi.labels | nindent 4 }}
  {{- end }}
spec:
  jobTargetRef:
    parallelism: 1 
    completions: 1
    activeDeadlineSeconds: {{ .Values.sdWebuiInferenceApi.scaling.activeDeadlineSeconds }}
    backoffLimit: {{ .Values.sdWebuiInferenceApi.scaling.backoffLimit }}
    template:
      metadata:
        labels:
          app: sd-webui-inference-api
        {{- include "sdchart.selectorLabels" . | nindent 8 }}
      spec:
        shareProcessNamespace: true
        containers:
        - name: sd-webui-inference-api
          image: {{ .Values.sdWebuiInferenceApi.inferenceApi.image.repository }}:{{  .Values.sdWebuiInferenceApi.inferenceApi.image.tag }}
          resources:
            requests:
              "nvidia.com/gpu": 1
            limits:
              "nvidia.com/gpu": 1
          volumeMounts:
          - mountPath: {{ .Values.sdWebuiInferenceApi.inferenceApi.modelMountPath }}
            name: models
          imagePullPolicy: {{ .Values.sdWebuiInferenceApi.inferenceApi.imagePullPolicy }}
          env:
          - name: SD_MODEL_CHECKPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ include "sdchart.fullname" . }}-sd-webui-config
                key: SD_MODEL_CHECKPOINT
          {{- if .Values.sdWebuiInferenceApi.inferenceApi.extraEnv }}
          {{- toYaml .Values.sdWebuiInferenceApi.inferenceApi.extraEnv | nindent 10 }}
          {{- end }}
        - name: sd-webui-queue-agent
          envFrom:
          - configMapRef:
              name: {{ include "sdchart.fullname" . }}-sd-webui-config
          env:
          {{- if .Values.sdWebuiInferenceApi.queueAgent.extraEnv }}
          {{- toYaml .Values.sdWebuiInferenceApi.queueAgent.extraEnv | nindent 10 }}
          {{- end }}
          {{- if .Values.sdWebuiInferenceApi.queueAgent.XRay.enabled }}
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: localhost:2000
          - name: AWS_XRAY_CONTEXT_MISSING
            value: IGNORE_ERROR
          {{- end }}
          image: {{ .Values.sdWebuiInferenceApi.queueAgent.image.repository }}:{{ .Values.sdWebuiInferenceApi.queueAgent.image.tag }}
          name: sd-webui-queue-agent
          imagePullPolicy: {{ .Values.sdWebuiInferenceApi.queueAgent.imagePullPolicy }}
          volumeMounts:
          - mountPath: /tmp/models
            name: models
          resources:
          {{- toYaml .Values.sdWebuiInferenceApi.queueAgent.resources | nindent 10 }}
        {{- if .Values.sdWebuiInferenceApi.queueAgent.XRay.enabled }}
        - name: xray-daemon
          image: public.ecr.aws/xray/aws-xray-daemon:3.3.7
          ports:
          - containerPort: 2000
            protocol: UDP
        {{- end }}
        serviceAccountName: {{ .Values.sdWebuiInferenceApi.serviceAccountName }}
        scalingStrategy: 
          strategy: accurate
        terminationGracePeriodSeconds: 60
        tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        - effect: NoSchedule
          key: runtime
          value: {{ include "sdchart.fullname" . }}
        volumes:
        - name: models
        {{- if .Values.sdWebuiInferenceApi.persistence.enabled }}
          persistentVolumeClaim:
            {{- if .Values.sdWebuiInferenceApi.persistence.existingClaim }}
            claimName: {{ .Values.sdWebuiInferenceApi.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "sdchart.fullname" . }}-model-claim
            {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}    
        - name: shared-data
          emptyDir: {}
  maxReplicaCount: {{ .Values.sdWebuiInferenceApi.scaling.maxReplicaCount }}
  pollingInterval: {{ .Values.sdWebuiInferenceApi.scaling.pollingInterval }}
  successfulJobsHistoryLimit: {{ .Values.sdWebuiInferenceApi.scaling.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.sdWebuiInferenceApi.scaling.failedJobsHistoryLimit }}
  triggers:
  - authenticationRef:
      name: {{ include "sdchart.fullname" . }}-keda-trigger-auth-aws-credentials
    metadata:
      awsRegion: {{ .Values.global.awsRegion }}
      identityOwner: operator
      queueLength: {{ quote .Values.sdWebuiInferenceApi.scaling.queueLength }}
      queueURL: {{ .Values.sdWebuiInferenceApi.queueAgent.sqsQueueUrl }}
      scaleOnInFlight: "{{ .Values.sdWebuiInferenceApi.scaling.scaleOnInFlight }}"
    type: aws-sqs-queue
{{- end }}