{{- if and (.Values.sdWebuiInferenceApi.scaling.enabled) (not .Values.sdWebuiInferenceApi.isJob) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sdchart.fullname" . }}-sd-webui-inference-api
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sdchart.labels" . | nindent 4 }}
  {{- if .Values.sdWebuiInferenceApi.labels }}
  {{- toYaml .Values.sdWebuiInferenceApi.labels | nindent 4 }}
  {{- end }}

  {{- if .Values.sdWebuiInferenceApi.annotations }}
  annotations:
  {{ toYaml .Values.sdWebuiInferenceApi.annotations | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .Values.sdWebuiInferenceApi.replicas }}
  selector:
    matchLabels:
      app: sd-webui-inference-api
    {{- include "sdchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sd-webui-inference-api
      {{- include "sdchart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: sd-webui-inference-api
        image: {{ .Values.sdWebuiInferenceApi.inferenceApi.image.repository }}:{{  .Values.sdWebuiInferenceApi.inferenceApi.image.tag }}
        env:
        - name: SD_MODEL_CHECKPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ include "sdchart.fullname" . }}-sd-webui-config
              key: SD_MODEL_CHECKPOINT
        {{- if .Values.sdWebuiInferenceApi.inferenceApi.extraEnv }}
        {{- toYaml .Values.sdWebuiInferenceApi.inferenceApi.extraEnv | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.sdWebuiInferenceApi.inferenceApi.resources | nindent 10 }}
        volumeMounts:
        - mountPath: {{ .Values.sdWebuiInferenceApi.inferenceApi.modelMountPath }}
          name: models
        imagePullPolicy: {{ .Values.sdWebuiInferenceApi.inferenceApi.imagePullPolicy }}
        startupProbe:
          httpGet:
            path: /sdapi/v1/memory
            port: 8080
          failureThreshold: 120
          periodSeconds: 1
      - name: sd-webui-queue-agent
        envFrom:
        - configMapRef:
            name: {{ include "sdchart.fullname" . }}-sd-webui-config
        env:
        {{- if .Values.sdWebuiInferenceApi.queueAgent.extraEnv }}
        {{- toYaml .Values.sdWebuiInferenceApi.queueAgent.extraEnv | nindent 10 }}
        {{- end }}
        {{- if .Values.sdWebuiInferenceApi.queueAgent.XRay.enabled }}
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: localhost:2000
        - name: AWS_XRAY_CONTEXT_MISSING
          value: IGNORE_ERROR
        {{- end }}
        image: {{ .Values.sdWebuiInferenceApi.queueAgent.image.repository }}:{{ .Values.sdWebuiInferenceApi.queueAgent.image.tag }}
        name: sd-webui-queue-agent
        imagePullPolicy: {{ .Values.sdWebuiInferenceApi.queueAgent.imagePullPolicy }}
        volumeMounts:
        - mountPath: /tmp/models
          name: models
        resources:
        {{- toYaml .Values.sdWebuiInferenceApi.queueAgent.resources | nindent 10 }}
      {{- if .Values.sdWebuiInferenceApi.queueAgent.XRay.enabled }}
      - name: xray-daemon
        image: public.ecr.aws/xray/aws-xray-daemon:3.3.7
        ports:
        - containerPort: 2000
          protocol: UDP
      {{- end }}
      serviceAccountName: {{ .Values.sdWebuiInferenceApi.serviceAccountName }}
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: runtime
        value: {{ include "sdchart.fullname" . }}
      volumes:
      - name: models
      {{- if .Values.sdWebuiInferenceApi.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.sdWebuiInferenceApi.persistence.existingClaim }}
          claimName: {{ .Values.sdWebuiInferenceApi.persistence.existingClaim }}
          {{- else }}
          claimName: {{ include "sdchart.fullname" . }}-model-claim
          {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
{{- end }}